name: network_tutorial
dependencies:
- certifi
- decorator
- freetype
- ipython
- jinja2
- jsonschema
- libpng
- libsodium
- markupsafe
- matplotlib
- networkx
- numpy
- openssl
- pandas
- pip
- pyparsing
- pyqt
- python
- python-dateutil
- pytz
- pyzmq
- qt
- readline
- setuptools
- sip
- six
- sqlite
- tk
- tornado
- xz
- zeromq
- zlib
- pip:
  - hiveplot

